version: "3.3"
services:
  redis:
    image: "redis:latest"
  graphql:
    image: codefly.azurecr.io/graphql:latest
    environment:
      DATABASE_URL: postgres://user:postgres@postgres:5432/connect
      B2C_AUTHORITY: https://codeflyb2c.b2clogin.com/codeflyb2c.onmicrosoft.com
      B2C_LOGIN_POLICY: B2C_1_CASpR
      REDIS_HOST: redis
    build:
      context: .
      dockerfile: docker/graphql/Dockerfile
    depends_on:
      - postgres
    links: 
      - postgres
    volumes:
      - ./prisma:/usr/src/app/prisma
      - ./graphql/src:/usr/src/app/graphql/src
      - ./graphql/index.ts:/usr/src/app/graphql/index.ts
      - ./lib:/usr/src/app/lib
    ports:
      - 8080:4000
    command: [bash, -c, "cd graphql && npm start"]
  www:
    image: codefly.azurecr.io/www:latest
    build:
      context: .
      dockerfile: docker/www/Dockerfile
    volumes:
      - ./www/src:/usr/src/app/www/src
    ports:
      - 80:80
    links:
      - graphql
    depends_on:
      - graphql
    command: [bash, -c, "cd www && npm start -- --port=80"]
  postgres:
    image: codefly.azurecr.io/postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: david@codefly.ninja
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8088:80
