name: Connect CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn setup
      - run: yarn lint
      - run: yarn test
  
  build-www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: docker build . -t codefly.azurecr.io/www:latest --file ./docker/www/Dockerfile

  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: docker build . -t codefly.azurecr.io/www:latest --file ./docker/api/Dockerfile

  build-graphql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: docker build . -t codefly.azurecr.io/www:latest --file ./docker/graphql/Dockerfile